version: '3'

services:
  bot:
    build: .
    depends_on:
      - redis
    volumes:
      - '.:/usr/src/app'
    env_file: '.env'

  redis:
    image: 'redis:6.0-rc'
    environment:
      - 'TELEGRAM_SESSION_HOST=localhost'
    ports:
      - '6379:6379'
